### ISSUE TITLE
It can't show icon on 32

### ISSUE THREAD

**Issue by ted423** [muzuiget/user_agent_overrider#12]
I disable and enable it ,the icon disapear

**Comment by apm** [comment]
The 'disabled' state icon now does not show in the production release of Firefox (35).

**Comment by dholbert** [comment]
Firefox 36 was released this week, so this now reproduces in the actual Firefox release.  (Just install the addon, and you get an invisible button on your toolbar.)

Any ETA on a fix here?

**Comment by dholbert** [comment]
Thanks!
