### ISSUE TITLE
[ES6][ff-nightly] Convert const and let to var's (Bug 950547)

### ISSUE THREAD

**Issue by Halibut80** [muzuiget/user_agent_overrider#16]
<a href="https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/">https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/</a>

**Comment by muzuiget** [comment]
Referrer https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/
