### ISSUE TITLE
Mobile-Detect easily read the correct Uuser Agent

### ISSUE THREAD

**Issue by semeion** [muzuiget/user_agent_overrider#17]
The Mobile-Detect github project can bypass user_agent_overrider and show correct information:

This routine get/steal the correct UA:
https://github.com/serbanghita/Mobile-Detect/blob/master/Mobile_Detect.php#L557-L569

I think could be nice an fix/update, because this firefox addon isn´t working very well anymore, but i like him so much to deinstall.

Thanks in advanced,

**Comment by muzuiget** [comment]
I still don't understand what your mean, are you reallay enable/active the extension?

**Comment by semeion** [comment]
That project can get the original User Agent of browser, bypassing what was set with user_agent_overrider.

Why change the UA if it can be easly detected?

**Comment by muzuiget** [comment]
It doesn't make sense, can you double check it with Firefox DevTool Network panel?

**Comment by semeion** [comment]
I have solved my problem, you can close this thread, and thank you anyways.

**Comment by muzuiget** [comment]
So, what is the reason?
