### ISSUE TITLE
Issue with Mint or Add-ons page?

### ISSUE THREAD

**Issue by j0nn0** [muzuiget/user_agent_overrider#19]
Using FF 44.0.2 for Linux Mint. Attempting to add user agent overrider from add ons site has error: "The add-on downloaded from this site could not be installed because it appears to be corrupt.

**Comment by muzuiget** [comment]
It maybe a network problem when you downloading from AMO. Have you retry it? Or you can download the .xpi file to harddisk, then use arcihve tools(like unzip/7z) to extract it, check the .xpi file  integrality.
