### ISSUE TITLE
Site-specific config

### ISSUE THREAD

**Issue by lassana** [muzuiget/user_agent_overrider#21]
It would be nice if UAO could allow set an user-agent string only for a few domains.
Like `domain=example.com: Mozilla/5.0 (Android 4.4; Tablet; rv:41.0) Gecko/41.0 Firefox/41.0`.

**Comment by muzuiget** [comment]
Current project code base is hard to implement this feature. 

But my other project https://github.com/muzuiget/referrer_control is easier to implement this, just change each `Referrer` to `User Agent`.

**Comment by Gitoffthelawn** [comment]
Or maybe one extension to do both.
