### ISSUE TITLE
A possible solution for #18?

### ISSUE THREAD

**Issue by laserstrike** [muzuiget/user_agent_overrider#22]
Please forgive me for linking a different add-on, but Random Agent Spoofer seems to fool www.browserleaks.com/javascript in the platform section. Maybe there's something in its source that can help your add-on? 

https://github.com/dillbyrne/random-agent-spoofer

I don't know much so I don't know where to look, etc.
And I don't like using unnecessary stuff that's why I prefer yours. But thanks either way.

**Comment by muzuiget** [comment]
As I said in #18, it is not technology problem.

GUI is the hardest part, the extension almost 90% code is about GUI. Implement this feature is easy if without GUI. If add GUI for normal user. I need to redesign UI layout, I need to do i18n, I need to keep version compatible. And Mozilla is deprecate XUL, and XUL docs is hard to read.

So I lost interesting on this, and I don't have time on this.
