### ISSUE TITLE
UA切换后，会造成一些窗口功能失效、无法关闭

### ISSUE THREAD

**Issue by FateRover** [muzuiget/user_agent_overrider#24]
一、0.4.1的版本，切换成安卓/chrome40 然后stylish 选择新建样式，粘点css进去，点击预览没反应，点击保存没反应。
二、还是切成安卓，F12把默认开发工具里的代码速记器勾上，然后开俩速记，随便输点东西保存下，也不能保存（几率不能保存），然后关闭firefox主窗口，这俩速记器不会随着关闭，点击关闭也没反应。
从nightly46开始的，45正式版也存在。我不知道这是firefox的问题还是扩展的问题，据说45一些窗口的路径改了，另外一个切换UA的扩展没这个问题。

**Comment by FateRover** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1261652  好吧

**Comment by muzuiget** [comment]
看上去就是 CodeMirror 那个编辑器的问题，这个扩展就是修改 `general.useragent.override` 这个 配置而已。
