### ISSUE TITLE
Hovering over UAO button in menu panel does not highlight it

### ISSUE THREAD

**Issue by Gitoffthelawn** [muzuiget/user_agent_overrider#27]
Unlike other items in the menu panel, the UAO button does not highlight on hover when 'Default' is selected.

**Comment by muzuiget** [comment]
What is  "highlight", there are a tool-tips will be showed.

**Comment by Gitoffthelawn** [comment]
The tooltip shows properly.

When the user hovers the cursor over the UAO button in the menu panel, the entire button should become highlighted (with a gray color, by default).  All Firefox standard built-in toolbar buttons do this, as well as buttons for other extensions.

**Comment by RyanZim** [comment]
Works fine for me.

**Comment by Gitoffthelawn** [comment]
@RyanZim Thanks for your contribution.  What OS and version of Firefox did you test it on?  I just tested it on Firefox 48.0.2 on Windows 7 SP1, and it did not work.

**Comment by RyanZim** [comment]
Lubuntu (Linux), Firefox 48.

**Comment by Gitoffthelawn** [comment]
Thanks.  That explains the difference.

**Comment by RyanZim** [comment]
I just tested it on Firefox 48.0.2 on Windows 7, and it _does_ work.

**Comment by Gitoffthelawn** [comment]
Doesn't work on all of the Windows 7 systems I tested.

**Comment by Gitoffthelawn** [comment]
OK, I debugged the code.

Here is what is causing the issue:

In Firefox's `chrome://browser/content/browser.xul`, there is the following declaration:

```
panelview .toolbarbutton-1:not(:-moz-any([disabled],[open],:active)):hover,
toolbarbutton.subviewbutton:not(:-moz-any([disabled],[open],:active)):hover,
menu.subviewbutton:not(:-moz-any([disabled],:active))[_moz-menuactive],
menuitem.subviewbutton:not(:-moz-any([disabled],:active))[_moz-menuactive],
.share-provider-button:not(:-moz-any([disabled],[open],:active)):hover:not([checked="true"]),
.widget-overflow-list .toolbarbutton-1:not(:-moz-any([disabled],[open],:active)):hover,
.toolbaritem-combined-buttons:-moz-any(:not([cui-areatype="toolbar"]), [overflowedItem=true]) > toolbarbutton:not(:-moz-any([disabled],[open],:active)):hover {
  background-color: hsla(210,4%,10%,.08);
  border-color: hsla(210,4%,10%,.11);
}

```
This code prevents UAO's button from being highlighted on hover whenever it is in the menu panel and 'Default' is selected.  This is because UAO sets the button's `disabled` attribute to `yes` when `Default` is selected by the user.  As you can see by the code above, this prevents the highlighting on hover.

Not sure why RyanZim doesn't experience this.  Maybe his computers are magical.

**Comment by Gitoffthelawn** [comment]
I wrote the fix for this issue in this pull request: https://github.com/muzuiget/user_agent_overrider/pull/28

**Comment by Gitoffthelawn** [comment]
@muzuiget Can you merge the pull request and publish the resultant code?

If you don't have time, you can add me as a contributor, and I can do it.

**Comment by muzuiget** [comment]
This project in [bugfix mode](https://github.com/muzuiget/user_agent_overrider/blob/master/README.md) now.

I suggest you request this feature to User Agent Switcher.

**Comment by Gitoffthelawn** [comment]
Technically, it's a bug. ;)

I guessing his extension won't include the bug because I think he said it's all new code.
