### ISSUE TITLE
Android String option not providing service

### ISSUE THREAD

**Issue by Voltixdark** [muzuiget/user_agent_overrider#29]
I have an Android Phone: ZTE ZMAX version 4.4.4 with MetroPCS. I have tried for the last few months now trying to use the android string option since my phone's data has been throttled. It used to work before, but no longer. I have attempted to change the string myself by changing versions numbers of the browsers according to the versions that are on my phone. And it is a no go. Usually sometimes when this was working before i could switch to even any other string to get high speed back when I was throttled. So I do not know what is the matter. I appreciate all the help I can get. Thanks

**Comment by muzuiget** [comment]
It look like is your ISP fix that trick, so it is not the UAO bug.
