### ISSUE TITLE
Toolbar button tooltip improvements

### ISSUE THREAD

**Issue by pythonicca** [muzuiget/user_agent_overrider#33]
Some suggestions that would make the tooltip a little more useful (as the icon already indicates whether the extension is working or not)

- Replace 'not working now' with 'browser default'
- Replace 'working now' with the name of the useragent that is currently selected.

**Comment by muzuiget** [comment]
This project in [bugfix mode](https://github.com/muzuiget/user_agent_overrider/blob/master/README.md) now.

I suggest you request this feature to User Agent Switcher.
