### ISSUE TITLE
Options window improvements

### ISSUE THREAD

**Issue by pythonicca** [muzuiget/user_agent_overrider#34]
When I choose 'preferences' from the UAO toolbar button an 'Options' window opens.

The Options window is 480x380 (non-resizable) which makes adding or editing (long) useragent strings tedious.

It would be a huge improvement if this window (along with the text area) could be resized with a gripper in the bottom right hand corner. Alternatively you could allow us to maximize the window by re-enabling the window's maximize button. (the text area would need to be flexible for this to work correctly)

If the user chooses to resize the window it would be nice if that preference was saved and restored the next time it's open.

**Comment by muzuiget** [comment]
This project in [bugfix mode](https://github.com/muzuiget/user_agent_overrider/blob/master/README.md) now.

I suggest you request this feature to User Agent Switcher.
