### ISSUE TITLE
Useragent entries improvements

### ISSUE THREAD

**Issue by pythonicca** [muzuiget/user_agent_overrider#35]
It would be great if the useragent entries could be parsed into submenus where applicable. For example the menu includes the following default useragents:

```
Windows / IE 11
Windows / Edge
Windows / Chrome
```

(When I click on the UAO button I see those three listed as-is.)

If you used the '/' as a delimiter you could parse them into a single 'Windows' submenu which (when clicked) would list them like so:

```
IE 11
Edge
Chrome
```

**Comment by muzuiget** [comment]
This project in [bugfix mode](https://github.com/muzuiget/user_agent_overrider/blob/master/README.md) now.

I suggest you request this feature to User Agent Switcher.
