### ISSUE TITLE
Change User-Agent programmatically 

### ISSUE THREAD

**Issue by wice90** [muzuiget/user_agent_overrider#37]
I am using python + selenium + firefox for one web-automation project. For every web page visited I need new user-agent. Is there any way to insert new user-agent and activate it programmatically?

**Comment by muzuiget** [comment]
Just change `general.useragent.override` item in `about:config`.

**Comment by wice90** [comment]
Any clues how can I do that automatically?

**Comment by Atavic** [comment]
random-agent-spoofer or secret-agent addons do that.
