### ISSUE TITLE
Allow resetting to default

### ISSUE THREAD

**Issue by hfiguiere** [muzuiget/user_agent_overrider#9]
It didn't seem obvious but the add-on menu lack a "default" entry to reset to the default.

**Comment by goetzc** [comment]
Why not, additionally another menu entry named `Default`?

**Comment by Gitoffthelawn** [comment]
@hfiguiere @goetzc If you are interested, you can add a line to userChrome.css like this:
#useragentoverrider-button:not([disabled]) { background-color: lightblue !important; }
to make the button light blue when enabled.

Or you can do something like:
#useragentoverrider-button[disabled] { background-color: red !important; }
to make the button red when not enabled.

Mix and match to suit your needs!
